### 200 Пользователи - Регистрация нового пользователя
POST http://127.0.0.1:8000/api/users/
Content-Type: application/json

{
  "email": "ant@ant.ru",
  "username": "Betty2",
  "first_name": "Betty",
  "last_name": "Mott",
  "password": "121314hi"
}

### 400 Пользователи - Регистрация нового пользователя
POST http://127.0.0.1:8000/api/users/
Content-Type: application/json

{
  "email": "nnnba@ant.ru",
  "username": "agara",
  "first_name": "",
  "last_name": "",
  "password": "121314hi"
}


### Пользователи - Получение токена для суперпользователя
POST http://127.0.0.1:8000/api/auth/token/login/
Content-Type: application/json

{
  "password": "admin5",
  "email": "a@adm.ru"
}

### Пользователи - Получение токена для пользователя regular_user
POST http://127.0.0.1:8000/api/auth/token/login/
Content-Type: application/json

{
  "password": "Elen5Elen5",
  "email": "b@b.com"
}

### Пользователи - Получение токена для пользователя Betty
POST http://127.0.0.1:8000/api/auth/token/login/
Content-Type: application/json

{
  "password": "121314hi",
  "email": "ant@ant.ru"
}

### Пользователи - Получение токена для пользователя nina
POST http://127.0.0.1:8000/api/auth/token/login/
Content-Type: application/json

{
  "password": "121314hi",
  "email": "nn@ant.ru"
}


### Пользователи - Токен суперпользователя admin2
@token = cea6a65d6f77f38a7dbc94c0328054292a512dcd

### Пользователи - Токен пользователя regular_user
@token2 = b90cd49016e9a034f64a226da13842b03da266c0

### Пользователи - Токен пользователя Betty2
@token3 = a7ad03fbe989a62dd155de6c808bbdf84e74e885

### Пользователи - Токен пользователя nina
@token4 = 07250f472901dab8aee912479c8774d129cfef7d


### Пользователи - Список пользователей
GET http://127.0.0.1:8000/api/users/


### 200 Пользователи - Профиль пользователя
GET http://127.0.0.1:8000/api/users/3/
Authorization: Token {{token2}}

### 401 Пользователи - Профиль пользователя
GET http://127.0.0.1:8000/api/users/3/

### 404 Пользователи - Профиль пользователя
GET http://127.0.0.1:8000/api/users/45/
Authorization: Token {{token2}}


### 200 Пользователи - Текущий пользователь
GET http://127.0.0.1:8000/api/users/me/
Authorization: Token {{token3}}

### 401 Пользователи - Текущий пользователь
GET http://127.0.0.1:8000/api/users/me/


### 204 Пользователи - Изменение пароля
POST http://127.0.0.1:8000/api/users/set_password/
Content-Type: application/json
Authorization: Token {{token4}}

{
"new_password": "hehe121314",
"current_password": "121314hi"
}

### 400 Пользователи - Изменение пароля
POST http://127.0.0.1:8000/api/users/set_password/
Content-Type: application/json
Authorization: Token {{token4}}

{
"new_password": "11",
"current_password": "hehe121314"
}

### 401 Пользователи - Изменение пароля
POST http://127.0.0.1:8000/api/users/set_password/
Content-Type: application/json

{
"new_password": "11",
"current_password": "hehe121314"
}


### 204 Пользователи - Удаление токена
POST http://127.0.0.1:8000/api/auth/token/logout/
Content-Type: application/json
Authorization: Token {{token4}}

### 401 Пользователи - Удаление токена
POST http://127.0.0.1:8000/api/auth/token/logout/
Content-Type: application/json



### 200 Теги - Cписок тегов
GET http://127.0.0.1:8000/api/tags/


### 200 Теги - Получение тега
GET http://127.0.0.1:8000/api/tags/1/

### 404 Теги - Получение тега
GET http://127.0.0.1:8000/api/tags/356/



### 200 Рецепты - Список рецептов
GET http://127.0.0.1:8000/api/recipes/

### 200 Рецепты - Список рецептов с фильтрацией
GET http://127.0.0.1:8000/api/recipes/?tags=obed


### 201 Рецепты - Создать рецепт
POST http://127.0.0.1:8000/api/recipes/
Content-Type: application/json
Authorization: Token {{token3}}

{
  "ingredients": [
      {
      "id": 1123,
      "amount": 10
      }
    ],
  "tags": [
      1,
      2
    ],
  "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg==",
  "name": "Test",
  "text": "Test description",
  "cooking_time": 10
}

### 400 Рецепты - Создать рецепт
POST http://127.0.0.1:8000/api/recipes/
Content-Type: application/json
Authorization: Token {{token3}}

{
  "ingredients": [
      {
      "id": 1123,
      "amount": 10
      }
    ],
  "tags": [
      1,
      2
    ],
  "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg==",
  "name": "",
  "text": "Test description",
  "cooking_time": 0
}

### 401 Рецепты - Создать рецепт
POST http://127.0.0.1:8000/api/recipes/
Content-Type: application/json

{
  "ingredients": [
      {
      "id": 1123,
      "amount": 10
      }
    ],
  "tags": [
      1,
      2
    ],
  "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg==",
  "name": "Test",
  "text": "Test description",
  "cooking_time": 10
}

### 404 Рецепты - Создать рецепт
POST http://127.0.0.1:8000/api/recipes1/
Content-Type: application/json
Authorization: Token {{token3}}

{
  "ingredients": [
      {
      "id": 1123,
      "amount": 10
      }
    ],
  "tags": [
      1,
      2
    ],
  "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg==",
  "name": "Test",
  "text": "Test description",
  "cooking_time": 10
}


### 200 Рецепты - Получение рецепта
GET http://127.0.0.1:8000/api/recipes/2


### 200 Рецепты - Обновление рецепта
PATCH http://127.0.0.1:8000/api/recipes/16/
Content-Type: application/json
Authorization: Token {{token3}}

{
  "ingredients": [
      {
      "id": 1123,
      "amount": 10
      }
    ],
  "tags": [
      1,
      2
    ],
  "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg==",
  "name": "New Title",
  "text": "Test description",
  "cooking_time": 10
}

### 400 Рецепты - Обновление рецепта
PATCH http://127.0.0.1:8000/api/recipes/16/
Content-Type: application/json
Authorization: Token {{token3}}

{
  "ingredients": [
      {
      "id": 1123,
      "amount": 0
      }
    ],
  "tags": [
      1,
      2
    ],
  "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg==",
  "name": "New Title",
  "text": "Test description",
  "cooking_time": 10
}

### 401 Рецепты - Обновление рецепта
PATCH http://127.0.0.1:8000/api/recipes/16/
Content-Type: application/json

{
  "ingredients": [
      {
      "id": 1123,
      "amount": 10
      }
    ],
  "tags": [
      1,
      2
    ],
  "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg==",
  "name": "New Title",
  "text": "Test description",
  "cooking_time": 10
}

### 403 Рецепты - Обновление рецепта
PATCH http://127.0.0.1:8000/api/recipes/11/
Content-Type: application/json
Authorization: Token {{token3}}

{
  "ingredients": [
      {
      "id": 1123,
      "amount": 10
      }
    ],
  "tags": [
      1,
      2
    ],
  "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg==",
  "name": "New Title",
  "text": "Test description",
  "cooking_time": 10
}

### 404 Рецепты - Обновление рецепта
PATCH http://127.0.0.1:8000/api/recipes/123/
Content-Type: application/json
Authorization: Token {{token3}}

{
  "ingredients": [
      {
      "id": 1123,
      "amount": 10
      }
    ],
  "tags": [
      1,
      2
    ],
  "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg==",
  "name": "New Title",
  "text": "Test description",
  "cooking_time": 10
}


### 204 Рецепты - Удаление рецепта
DELETE http://127.0.0.1:8000/api/recipes/6/
Authorization: Token {{token2}}

### 401 Рецепты - Удаление рецепта
DELETE http://127.0.0.1:8000/api/recipes/16/

### 403 Рецепты - Удаление рецепта
DELETE http://127.0.0.1:8000/api/recipes/16/
Authorization: Token {{token2}}

### 403 Рецепты - Удаление рецепта
DELETE http://127.0.0.1:8000/api/recipes/123/
Authorization: Token {{token3}}



### 200 Список покупок - Скачать список покупок
GET http://127.0.0.1:8000/api/recipes/download_shopping_cart/
Authorization: Token {{token3}}

### 401 Список покупок - Скачать список покупок
GET http://127.0.0.1:8000/api/recipes/download_shopping_cart/


### 201 Список покупок - Добавить рецепт в список покупок
POST http://127.0.0.1:8000/api/recipes/6/shopping_cart/
Authorization: Token {{token3}}

### 400 Список покупок - Добавить рецепт в список покупок
POST http://127.0.0.1:8000/api/recipes/6/shopping_cart/
Authorization: Token {{token3}}

### 401 Список покупок - Добавить рецепт в список покупок
POST http://127.0.0.1:8000/api/recipes/6/shopping_cart/


### 204 Список покупок - Удалить рецепт из списка покупок
DELETE http://127.0.0.1:8000/api/recipes/5/shopping_cart/
Authorization: Token {{token3}}

### 400 Список покупок - Удалить рецепт из списка покупок
DELETE http://127.0.0.1:8000/api/recipes/5/shopping_cart/
Authorization: Token {{token3}}

### 401 Список покупок - Удалить рецепт из списка покупок
DELETE http://127.0.0.1:8000/api/recipes/5/shopping_cart/



### 201 Избранное - Добавить рецепт в избранное
POST http://127.0.0.1:8000/api/recipes/6/favorite/
Authorization: Token {{token3}}

### 400 Избранное - Добавить рецепт в избранное
POST http://127.0.0.1:8000/api/recipes/6/favorite/
Authorization: Token {{token3}}

### 401 Избранное - Добавить рецепт в избранное
POST http://127.0.0.1:8000/api/recipes/6/favorite/


### 204 Избранное - Удалить рецепт из избранного
DELETE http://127.0.0.1:8000/api/recipes/3/favorite/
Authorization: Token {{token3}}

### 400 Избранное - Удалить рецепт из избранного
DELETE http://127.0.0.1:8000/api/recipes/3/favorite/
Authorization: Token {{token3}}

### 401 Избранное - Удалить рецепт из избранного
DELETE http://127.0.0.1:8000/api/recipes/3/favorite/



### 200 Подписки - Мои подписки
GET http://127.0.0.1:8000/api/users/subscriptions/
Authorization: Token {{token3}}

### 401 Подписки - Мои подписки
GET http://127.0.0.1:8000/api/users/subscriptions/


### 201 Подписки - Подписаться на пользователя
POST http://127.0.0.1:8000/api/users/4/subscribe/
Authorization: Token {{token3}}

### 400 Подписки - Подписаться на пользователя
POST http://127.0.0.1:8000/api/users/3/subscribe/
Authorization: Token {{token3}}

### 401 Подписки - Подписаться на пользователя
POST http://127.0.0.1:8000/api/users/3/subscribe/

### 404 Подписки - Подписаться на пользователя
POST http://127.0.0.1:8000/api/users/43/subscribe/
Authorization: Token {{token3}}


### 204 Подписки - Отписаться от пользователя
DELETE http://127.0.0.1:8000/api/users/4/subscribe/
Authorization: Token {{token3}}

### 400 Подписки - Отписаться от пользователя
DELETE http://127.0.0.1:8000/api/users/5/subscribe/
Authorization: Token {{token3}}

### 401 Подписки - Отписаться от пользователя
DELETE http://127.0.0.1:8000/api/users/3/subscribe/

### 404 Подписки - Отписаться от пользователя
DELETE http://127.0.0.1:8000/api/users/43/subscribe/
Authorization: Token {{token3}}



### 200 Ингредиенты - Список ингредиентов
GET http://127.0.0.1:8000/api/ingredients/


### 200 Ингредиенты - Получение ингредиента
GET http://127.0.0.1:8000/api/ingredients/45/
