# Generated by Django 4.0.3 on 2022-05-24 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_rename_shopingcart_shoppingcart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientforrecipe',
            old_name='ingredient',
            new_name='ingredients',
        ),
    ]
