# Generated by Django 4.0.3 on 2022-05-25 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_rename_ingredient_ingredientforrecipe_ingredients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientforrecipe',
            old_name='ingredients',
            new_name='ingredient',
        ),
    ]
