# Generated by Django 4.0.3 on 2022-05-02 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_alter_ingredient_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['id'], 'verbose_name': 'Ingredient', 'verbose_name_plural': 'Ingredients'},
        ),
    ]
